name: calculator
description: A new Flutter project

publish_to: 'none' # Optional: Remove if you are planning to publish your package

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


environment:
  sdk: ">=3.5.0 <4.0.0"

flutter:
  uses-material-design: true
